connector:
  id: 1
  boss-count: 5
  worker-count: 10
  accept-port: 9996
  so-backlog: 5000
  message-receiver: kafka
  mq-allocator: range
  topic-list:
    - xx.xx.xx.xx:2181=topic-1
    - xx.xx.xx.xx:2181=topic-2
    -
  zk:
    connect-str: xx.xx.xx.xx:2181
spring:
  profiles:
    active: dev
  application:
    name: connector
  redis:
    client-type: lettuce
    port: 6379
    host: xx.xx.xx.xx
dubbo:
  application:
    name: connector
    qos-port: 22224
    enable-file-cache: off
  protocol:
    name: tri
    port: -1
  registry:
    address: zookeeper://xx.xx.xx.xx?client=curator