// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_protocol.proto

package com.fy.chatserver.communicate.proto;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SInnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SInner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DataType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.DataType type = 1;</code>
     * @return The type.
     */
    com.fy.chatserver.communicate.proto.ClientProto.DataType getType();

    /**
     * <code>int64 ack = 2;</code>
     * @return The ack.
     */
    long getAck();

    /**
     * <code>.ServerMsg msg = 3;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.ServerMsg msg = 3;</code>
     * @return The msg.
     */
    com.fy.chatserver.communicate.proto.ServerProto.ServerMsg getMsg();
    /**
     * <code>.ServerMsg msg = 3;</code>
     */
    com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder getMsgOrBuilder();

    /**
     * <code>.Notification notification = 4;</code>
     * @return Whether the notification field is set.
     */
    boolean hasNotification();
    /**
     * <code>.Notification notification = 4;</code>
     * @return The notification.
     */
    com.fy.chatserver.communicate.proto.ClientProto.Notification getNotification();
    /**
     * <code>.Notification notification = 4;</code>
     */
    com.fy.chatserver.communicate.proto.ClientProto.NotificationOrBuilder getNotificationOrBuilder();

    /**
     * <code>.Heartbeat heartbeat = 5;</code>
     * @return Whether the heartbeat field is set.
     */
    boolean hasHeartbeat();
    /**
     * <code>.Heartbeat heartbeat = 5;</code>
     * @return The heartbeat.
     */
    com.fy.chatserver.communicate.proto.ClientProto.Heartbeat getHeartbeat();
    /**
     * <code>.Heartbeat heartbeat = 5;</code>
     */
    com.fy.chatserver.communicate.proto.ClientProto.HeartbeatOrBuilder getHeartbeatOrBuilder();

    public com.fy.chatserver.communicate.proto.ServerProto.SInner.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code SInner}
   */
  public static final class SInner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SInner)
      SInnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SInner.newBuilder() to construct.
    private SInner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SInner() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SInner();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SInner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              ack_ = input.readInt64();
              break;
            }
            case 26: {
              com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder subBuilder = null;
              if (dataCase_ == 3) {
                subBuilder = ((com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 3;
              break;
            }
            case 34: {
              com.fy.chatserver.communicate.proto.ClientProto.Notification.Builder subBuilder = null;
              if (dataCase_ == 4) {
                subBuilder = ((com.fy.chatserver.communicate.proto.ClientProto.Notification) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.fy.chatserver.communicate.proto.ClientProto.Notification.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.fy.chatserver.communicate.proto.ClientProto.Notification) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 4;
              break;
            }
            case 42: {
              com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.Builder subBuilder = null;
              if (dataCase_ == 5) {
                subBuilder = ((com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 5;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fy.chatserver.communicate.proto.ServerProto.internal_static_SInner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fy.chatserver.communicate.proto.ServerProto.internal_static_SInner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fy.chatserver.communicate.proto.ServerProto.SInner.class, com.fy.chatserver.communicate.proto.ServerProto.SInner.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      MSG(3),
      NOTIFICATION(4),
      HEARTBEAT(5),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 3: return MSG;
          case 4: return NOTIFICATION;
          case 5: return HEARTBEAT;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.DataType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.DataType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.fy.chatserver.communicate.proto.ClientProto.DataType getType() {
      @SuppressWarnings("deprecation")
      com.fy.chatserver.communicate.proto.ClientProto.DataType result = com.fy.chatserver.communicate.proto.ClientProto.DataType.valueOf(type_);
      return result == null ? com.fy.chatserver.communicate.proto.ClientProto.DataType.UNRECOGNIZED : result;
    }

    public static final int ACK_FIELD_NUMBER = 2;
    private long ack_;
    /**
     * <code>int64 ack = 2;</code>
     * @return The ack.
     */
    @java.lang.Override
    public long getAck() {
      return ack_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    /**
     * <code>.ServerMsg msg = 3;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return dataCase_ == 3;
    }
    /**
     * <code>.ServerMsg msg = 3;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg getMsg() {
      if (dataCase_ == 3) {
         return (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_;
      }
      return com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
    }
    /**
     * <code>.ServerMsg msg = 3;</code>
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder getMsgOrBuilder() {
      if (dataCase_ == 3) {
         return (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_;
      }
      return com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
    }

    public static final int NOTIFICATION_FIELD_NUMBER = 4;
    /**
     * <code>.Notification notification = 4;</code>
     * @return Whether the notification field is set.
     */
    @java.lang.Override
    public boolean hasNotification() {
      return dataCase_ == 4;
    }
    /**
     * <code>.Notification notification = 4;</code>
     * @return The notification.
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ClientProto.Notification getNotification() {
      if (dataCase_ == 4) {
         return (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_;
      }
      return com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance();
    }
    /**
     * <code>.Notification notification = 4;</code>
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ClientProto.NotificationOrBuilder getNotificationOrBuilder() {
      if (dataCase_ == 4) {
         return (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_;
      }
      return com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance();
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 5;
    /**
     * <code>.Heartbeat heartbeat = 5;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return dataCase_ == 5;
    }
    /**
     * <code>.Heartbeat heartbeat = 5;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ClientProto.Heartbeat getHeartbeat() {
      if (dataCase_ == 5) {
         return (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_;
      }
      return com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance();
    }
    /**
     * <code>.Heartbeat heartbeat = 5;</code>
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ClientProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      if (dataCase_ == 5) {
         return (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_;
      }
      return com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.fy.chatserver.communicate.proto.ClientProto.DataType.HEARTBEAT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (ack_ != 0L) {
        output.writeInt64(2, ack_);
      }
      if (dataCase_ == 3) {
        output.writeMessage(3, (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_);
      }
      if (dataCase_ == 4) {
        output.writeMessage(4, (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_);
      }
      if (dataCase_ == 5) {
        output.writeMessage(5, (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.fy.chatserver.communicate.proto.ClientProto.DataType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (ack_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ack_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_);
      }
      if (dataCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_);
      }
      if (dataCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fy.chatserver.communicate.proto.ServerProto.SInner)) {
        return super.equals(obj);
      }
      com.fy.chatserver.communicate.proto.ServerProto.SInner other = (com.fy.chatserver.communicate.proto.ServerProto.SInner) obj;

      if (type_ != other.type_) return false;
      if (getAck()
          != other.getAck()) return false;
      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 3:
          if (!getMsg()
              .equals(other.getMsg())) return false;
          break;
        case 4:
          if (!getNotification()
              .equals(other.getNotification())) return false;
          break;
        case 5:
          if (!getHeartbeat()
              .equals(other.getHeartbeat())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAck());
      switch (dataCase_) {
        case 3:
          hash = (37 * hash) + MSG_FIELD_NUMBER;
          hash = (53 * hash) + getMsg().hashCode();
          break;
        case 4:
          hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
          hash = (53 * hash) + getNotification().hashCode();
          break;
        case 5:
          hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
          hash = (53 * hash) + getHeartbeat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.SInner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fy.chatserver.communicate.proto.ServerProto.SInner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SInner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SInner)
        com.fy.chatserver.communicate.proto.ServerProto.SInnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fy.chatserver.communicate.proto.ServerProto.internal_static_SInner_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fy.chatserver.communicate.proto.ServerProto.internal_static_SInner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fy.chatserver.communicate.proto.ServerProto.SInner.class, com.fy.chatserver.communicate.proto.ServerProto.SInner.Builder.class);
      }

      // Construct using com.fy.chatserver.communicate.proto.ServerProto.SInner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        ack_ = 0L;

        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fy.chatserver.communicate.proto.ServerProto.internal_static_SInner_descriptor;
      }

      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.SInner getDefaultInstanceForType() {
        return com.fy.chatserver.communicate.proto.ServerProto.SInner.getDefaultInstance();
      }

      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.SInner build() {
        com.fy.chatserver.communicate.proto.ServerProto.SInner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.SInner buildPartial() {
        com.fy.chatserver.communicate.proto.ServerProto.SInner result = new com.fy.chatserver.communicate.proto.ServerProto.SInner(this);
        result.type_ = type_;
        result.ack_ = ack_;
        if (dataCase_ == 3) {
          if (msgBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = msgBuilder_.build();
          }
        }
        if (dataCase_ == 4) {
          if (notificationBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = notificationBuilder_.build();
          }
        }
        if (dataCase_ == 5) {
          if (heartbeatBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = heartbeatBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fy.chatserver.communicate.proto.ServerProto.SInner) {
          return mergeFrom((com.fy.chatserver.communicate.proto.ServerProto.SInner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fy.chatserver.communicate.proto.ServerProto.SInner other) {
        if (other == com.fy.chatserver.communicate.proto.ServerProto.SInner.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getAck() != 0L) {
          setAck(other.getAck());
        }
        switch (other.getDataCase()) {
          case MSG: {
            mergeMsg(other.getMsg());
            break;
          }
          case NOTIFICATION: {
            mergeNotification(other.getNotification());
            break;
          }
          case HEARTBEAT: {
            mergeHeartbeat(other.getHeartbeat());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fy.chatserver.communicate.proto.ServerProto.SInner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fy.chatserver.communicate.proto.ServerProto.SInner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.DataType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.DataType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DataType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ClientProto.DataType getType() {
        @SuppressWarnings("deprecation")
        com.fy.chatserver.communicate.proto.ClientProto.DataType result = com.fy.chatserver.communicate.proto.ClientProto.DataType.valueOf(type_);
        return result == null ? com.fy.chatserver.communicate.proto.ClientProto.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DataType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.fy.chatserver.communicate.proto.ClientProto.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DataType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long ack_ ;
      /**
       * <code>int64 ack = 2;</code>
       * @return The ack.
       */
      @java.lang.Override
      public long getAck() {
        return ack_;
      }
      /**
       * <code>int64 ack = 2;</code>
       * @param value The ack to set.
       * @return This builder for chaining.
       */
      public Builder setAck(long value) {
        
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ack = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAck() {
        
        ack_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ServerProto.ServerMsg, com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder, com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder> msgBuilder_;
      /**
       * <code>.ServerMsg msg = 3;</code>
       * @return Whether the msg field is set.
       */
      @java.lang.Override
      public boolean hasMsg() {
        return dataCase_ == 3;
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       * @return The msg.
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg getMsg() {
        if (msgBuilder_ == null) {
          if (dataCase_ == 3) {
            return (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_;
          }
          return com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
        } else {
          if (dataCase_ == 3) {
            return msgBuilder_.getMessage();
          }
          return com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
        }
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      public Builder setMsg(com.fy.chatserver.communicate.proto.ServerProto.ServerMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      public Builder setMsg(
          com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      public Builder mergeMsg(com.fy.chatserver.communicate.proto.ServerProto.ServerMsg value) {
        if (msgBuilder_ == null) {
          if (dataCase_ == 3 &&
              data_ != com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance()) {
            data_ = com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.newBuilder((com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 3) {
            msgBuilder_.mergeFrom(value);
          }
          msgBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
          }
          msgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder getMsgBuilder() {
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder getMsgOrBuilder() {
        if ((dataCase_ == 3) && (msgBuilder_ != null)) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 3) {
            return (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_;
          }
          return com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
        }
      }
      /**
       * <code>.ServerMsg msg = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ServerProto.ServerMsg, com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder, com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          if (!(dataCase_ == 3)) {
            data_ = com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
          }
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fy.chatserver.communicate.proto.ServerProto.ServerMsg, com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder, com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder>(
                  (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 3;
        onChanged();;
        return msgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ClientProto.Notification, com.fy.chatserver.communicate.proto.ClientProto.Notification.Builder, com.fy.chatserver.communicate.proto.ClientProto.NotificationOrBuilder> notificationBuilder_;
      /**
       * <code>.Notification notification = 4;</code>
       * @return Whether the notification field is set.
       */
      @java.lang.Override
      public boolean hasNotification() {
        return dataCase_ == 4;
      }
      /**
       * <code>.Notification notification = 4;</code>
       * @return The notification.
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ClientProto.Notification getNotification() {
        if (notificationBuilder_ == null) {
          if (dataCase_ == 4) {
            return (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_;
          }
          return com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance();
        } else {
          if (dataCase_ == 4) {
            return notificationBuilder_.getMessage();
          }
          return com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance();
        }
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      public Builder setNotification(com.fy.chatserver.communicate.proto.ClientProto.Notification value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          notificationBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      public Builder setNotification(
          com.fy.chatserver.communicate.proto.ClientProto.Notification.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          notificationBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      public Builder mergeNotification(com.fy.chatserver.communicate.proto.ClientProto.Notification value) {
        if (notificationBuilder_ == null) {
          if (dataCase_ == 4 &&
              data_ != com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance()) {
            data_ = com.fy.chatserver.communicate.proto.ClientProto.Notification.newBuilder((com.fy.chatserver.communicate.proto.ClientProto.Notification) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 4) {
            notificationBuilder_.mergeFrom(value);
          }
          notificationBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      public Builder clearNotification() {
        if (notificationBuilder_ == null) {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
          }
          notificationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      public com.fy.chatserver.communicate.proto.ClientProto.Notification.Builder getNotificationBuilder() {
        return getNotificationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ClientProto.NotificationOrBuilder getNotificationOrBuilder() {
        if ((dataCase_ == 4) && (notificationBuilder_ != null)) {
          return notificationBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 4) {
            return (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_;
          }
          return com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance();
        }
      }
      /**
       * <code>.Notification notification = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ClientProto.Notification, com.fy.chatserver.communicate.proto.ClientProto.Notification.Builder, com.fy.chatserver.communicate.proto.ClientProto.NotificationOrBuilder> 
          getNotificationFieldBuilder() {
        if (notificationBuilder_ == null) {
          if (!(dataCase_ == 4)) {
            data_ = com.fy.chatserver.communicate.proto.ClientProto.Notification.getDefaultInstance();
          }
          notificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fy.chatserver.communicate.proto.ClientProto.Notification, com.fy.chatserver.communicate.proto.ClientProto.Notification.Builder, com.fy.chatserver.communicate.proto.ClientProto.NotificationOrBuilder>(
                  (com.fy.chatserver.communicate.proto.ClientProto.Notification) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 4;
        onChanged();;
        return notificationBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ClientProto.Heartbeat, com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.Builder, com.fy.chatserver.communicate.proto.ClientProto.HeartbeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       * @return Whether the heartbeat field is set.
       */
      @java.lang.Override
      public boolean hasHeartbeat() {
        return dataCase_ == 5;
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       * @return The heartbeat.
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ClientProto.Heartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (dataCase_ == 5) {
            return (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_;
          }
          return com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance();
        } else {
          if (dataCase_ == 5) {
            return heartbeatBuilder_.getMessage();
          }
          return com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      public Builder setHeartbeat(com.fy.chatserver.communicate.proto.ClientProto.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      public Builder setHeartbeat(
          com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      public Builder mergeHeartbeat(com.fy.chatserver.communicate.proto.ClientProto.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (dataCase_ == 5 &&
              data_ != com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance()) {
            data_ = com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.newBuilder((com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 5) {
            heartbeatBuilder_.mergeFrom(value);
          }
          heartbeatBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
          }
          heartbeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      public com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.Builder getHeartbeatBuilder() {
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ClientProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
        if ((dataCase_ == 5) && (heartbeatBuilder_ != null)) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 5) {
            return (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_;
          }
          return com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.Heartbeat heartbeat = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ClientProto.Heartbeat, com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.Builder, com.fy.chatserver.communicate.proto.ClientProto.HeartbeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          if (!(dataCase_ == 5)) {
            data_ = com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.getDefaultInstance();
          }
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fy.chatserver.communicate.proto.ClientProto.Heartbeat, com.fy.chatserver.communicate.proto.ClientProto.Heartbeat.Builder, com.fy.chatserver.communicate.proto.ClientProto.HeartbeatOrBuilder>(
                  (com.fy.chatserver.communicate.proto.ClientProto.Heartbeat) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 5;
        onChanged();;
        return heartbeatBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SInner)
    }

    // @@protoc_insertion_point(class_scope:SInner)
    private static final com.fy.chatserver.communicate.proto.ServerProto.SInner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fy.chatserver.communicate.proto.ServerProto.SInner();
    }

    public static com.fy.chatserver.communicate.proto.ServerProto.SInner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SInner>
        PARSER = new com.google.protobuf.AbstractParser<SInner>() {
      @java.lang.Override
      public SInner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SInner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SInner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SInner> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ServerProto.SInner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serverId = 1;</code>
     * @return The serverId.
     */
    java.lang.String getServerId();
    /**
     * <code>string serverId = 1;</code>
     * @return The bytes for serverId.
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <code>.Msg msg = 2;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.Msg msg = 2;</code>
     * @return The msg.
     */
    com.fy.chatserver.communicate.proto.ClientProto.Msg getMsg();
    /**
     * <code>.Msg msg = 2;</code>
     */
    com.fy.chatserver.communicate.proto.ClientProto.MsgOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code ServerMsg}
   */
  public static final class ServerMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerMsg)
      ServerMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerMsg.newBuilder() to construct.
    private ServerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMsg() {
      serverId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serverId_ = s;
              break;
            }
            case 18: {
              com.fy.chatserver.communicate.proto.ClientProto.Msg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(com.fy.chatserver.communicate.proto.ClientProto.Msg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fy.chatserver.communicate.proto.ServerProto.internal_static_ServerMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fy.chatserver.communicate.proto.ServerProto.internal_static_ServerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.class, com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder.class);
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object serverId_;
    /**
     * <code>string serverId = 1;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      }
    }
    /**
     * <code>string serverId = 1;</code>
     * @return The bytes for serverId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.fy.chatserver.communicate.proto.ClientProto.Msg msg_;
    /**
     * <code>.Msg msg = 2;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>.Msg msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ClientProto.Msg getMsg() {
      return msg_ == null ? com.fy.chatserver.communicate.proto.ClientProto.Msg.getDefaultInstance() : msg_;
    }
    /**
     * <code>.Msg msg = 2;</code>
     */
    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ClientProto.MsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverId_);
      }
      if (msg_ != null) {
        output.writeMessage(2, getMsg());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverId_);
      }
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMsg());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fy.chatserver.communicate.proto.ServerProto.ServerMsg)) {
        return super.equals(obj);
      }
      com.fy.chatserver.communicate.proto.ServerProto.ServerMsg other = (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) obj;

      if (!getServerId()
          .equals(other.getServerId())) return false;
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fy.chatserver.communicate.proto.ServerProto.ServerMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerMsg)
        com.fy.chatserver.communicate.proto.ServerProto.ServerMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fy.chatserver.communicate.proto.ServerProto.internal_static_ServerMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fy.chatserver.communicate.proto.ServerProto.internal_static_ServerMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.class, com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.Builder.class);
      }

      // Construct using com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serverId_ = "";

        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fy.chatserver.communicate.proto.ServerProto.internal_static_ServerMsg_descriptor;
      }

      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg getDefaultInstanceForType() {
        return com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg build() {
        com.fy.chatserver.communicate.proto.ServerProto.ServerMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg buildPartial() {
        com.fy.chatserver.communicate.proto.ServerProto.ServerMsg result = new com.fy.chatserver.communicate.proto.ServerProto.ServerMsg(this);
        result.serverId_ = serverId_;
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) {
          return mergeFrom((com.fy.chatserver.communicate.proto.ServerProto.ServerMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fy.chatserver.communicate.proto.ServerProto.ServerMsg other) {
        if (other == com.fy.chatserver.communicate.proto.ServerProto.ServerMsg.getDefaultInstance()) return this;
        if (!other.getServerId().isEmpty()) {
          serverId_ = other.serverId_;
          onChanged();
        }
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fy.chatserver.communicate.proto.ServerProto.ServerMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fy.chatserver.communicate.proto.ServerProto.ServerMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serverId_ = "";
      /**
       * <code>string serverId = 1;</code>
       * @return The serverId.
       */
      public java.lang.String getServerId() {
        java.lang.Object ref = serverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serverId = 1;</code>
       * @return The bytes for serverId.
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        java.lang.Object ref = serverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverId = 1;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        
        serverId_ = getDefaultInstance().getServerId();
        onChanged();
        return this;
      }
      /**
       * <code>string serverId = 1;</code>
       * @param value The bytes for serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverId_ = value;
        onChanged();
        return this;
      }

      private com.fy.chatserver.communicate.proto.ClientProto.Msg msg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ClientProto.Msg, com.fy.chatserver.communicate.proto.ClientProto.Msg.Builder, com.fy.chatserver.communicate.proto.ClientProto.MsgOrBuilder> msgBuilder_;
      /**
       * <code>.Msg msg = 2;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>.Msg msg = 2;</code>
       * @return The msg.
       */
      public com.fy.chatserver.communicate.proto.ClientProto.Msg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? com.fy.chatserver.communicate.proto.ClientProto.Msg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      public Builder setMsg(com.fy.chatserver.communicate.proto.ClientProto.Msg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      public Builder setMsg(
          com.fy.chatserver.communicate.proto.ClientProto.Msg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      public Builder mergeMsg(com.fy.chatserver.communicate.proto.ClientProto.Msg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              com.fy.chatserver.communicate.proto.ClientProto.Msg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      public com.fy.chatserver.communicate.proto.ClientProto.Msg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      public com.fy.chatserver.communicate.proto.ClientProto.MsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              com.fy.chatserver.communicate.proto.ClientProto.Msg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>.Msg msg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fy.chatserver.communicate.proto.ClientProto.Msg, com.fy.chatserver.communicate.proto.ClientProto.Msg.Builder, com.fy.chatserver.communicate.proto.ClientProto.MsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fy.chatserver.communicate.proto.ClientProto.Msg, com.fy.chatserver.communicate.proto.ClientProto.Msg.Builder, com.fy.chatserver.communicate.proto.ClientProto.MsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerMsg)
    }

    // @@protoc_insertion_point(class_scope:ServerMsg)
    private static final com.fy.chatserver.communicate.proto.ServerProto.ServerMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fy.chatserver.communicate.proto.ServerProto.ServerMsg();
    }

    public static com.fy.chatserver.communicate.proto.ServerProto.ServerMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerMsg>
        PARSER = new com.google.protobuf.AbstractParser<ServerMsg>() {
      @java.lang.Override
      public ServerMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fy.chatserver.communicate.proto.ServerProto.ServerMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SInner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SInner_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025server_protocol.proto\032\025client_protocol" +
      ".proto\"\231\001\n\006SInner\022\027\n\004type\030\001 \001(\0162\t.DataTy" +
      "pe\022\013\n\003ack\030\002 \001(\003\022\031\n\003msg\030\003 \001(\0132\n.ServerMsg" +
      "H\000\022%\n\014notification\030\004 \001(\0132\r.NotificationH" +
      "\000\022\037\n\theartbeat\030\005 \001(\0132\n.HeartbeatH\000B\006\n\004da" +
      "ta\"0\n\tServerMsg\022\020\n\010serverId\030\001 \001(\t\022\021\n\003msg" +
      "\030\002 \001(\0132\004.MsgB4\n#com.fy.chatserver.commun" +
      "icate.protoB\013ServerProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fy.chatserver.communicate.proto.ClientProto.getDescriptor(),
        });
    internal_static_SInner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SInner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SInner_descriptor,
        new java.lang.String[] { "Type", "Ack", "Msg", "Notification", "Heartbeat", "Data", });
    internal_static_ServerMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerMsg_descriptor,
        new java.lang.String[] { "ServerId", "Msg", });
    com.fy.chatserver.communicate.proto.ClientProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
