// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

// Protobuf Java Version: 3.25.0
package com.feiyu.interfaces.idl;

public interface MsgHandleRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feiyu.interfaces.idl.MsgHandleRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>.com.feiyu.interfaces.idl.GenericMsgHandleResult res = 2;</code>
   * @return Whether the res field is set.
   */
  boolean hasRes();
  /**
   * <code>.com.feiyu.interfaces.idl.GenericMsgHandleResult res = 2;</code>
   * @return The res.
   */
  com.feiyu.interfaces.idl.GenericMsgHandleResult getRes();
  /**
   * <code>.com.feiyu.interfaces.idl.GenericMsgHandleResult res = 2;</code>
   */
  com.feiyu.interfaces.idl.GenericMsgHandleResultOrBuilder getResOrBuilder();
}
