// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

// Protobuf Java Version: 3.25.0
package com.feiyu.interfaces.idl;

public interface MsgHandleRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feiyu.interfaces.idl.MsgHandleRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 msgId = 1;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>int64 seq = 2;</code>
   * @return The seq.
   */
  long getSeq();
}
