// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

// Protobuf Java Version: 3.25.0
package com.feiyu.interfaces.idl;

public interface RouteReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feiyu.interfaces.idl.RouteReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 to = 1;</code>
   * @return The to.
   */
  long getTo();

  /**
   * <code>.Msg msg = 2;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.Msg msg = 2;</code>
   * @return The msg.
   */
  com.feiyu.base.proto.Messages.Msg getMsg();
  /**
   * <code>.Msg msg = 2;</code>
   */
  com.feiyu.base.proto.Messages.MsgOrBuilder getMsgOrBuilder();
}
