// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

// Protobuf Java Version: 3.25.0
package com.feiyu.interfaces.idl;

public interface SequenceRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feiyu.interfaces.idl.SequenceRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 seq = 1;</code>
   * @return The seq.
   */
  long getSeq();
}
