// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

// Protobuf Java Version: 3.25.0
package com.feiyu.interfaces.idl;

public interface SequenceReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feiyu.interfaces.idl.SequenceReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();
}
