server:
  port: 8080
ul-sequence:
  node-id: node-1
  start-uid: 1
  end-uid: 16384
  grow-step: 100
  segment-size: 1024
spring:
  profiles:
    active: dev

dubbo:
  application:
    name: ul-sequence
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://xxxx:2181
  config-center:
    address: zookeeper://xxxx:2181
  metadata-report:
    address: zookeeper://xxxx:2181