dubbo:
  application:
    name: consumer
  protocol:
    name: tri
    port: -1
  registry:
    address: zookeeper://xx.xx.xx.xx?client=curator
spring:
  application:
    name: service-consumer
  profiles:
    active: dev