dubbo:
  registry:
    address: zookeeper://111.230.15.9:2181?client=curator
spring:
  redis:
    host: 111.230.15.9
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.15.9:3306/fast_im?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: zolmk!@#.