spring:
  application:
    name: route
  profiles:
    active: dev
  redis:
    client-type: lettuce
    port: 6379
    host: xx.xx.xx.xx

dubbo:
  application:
    name: core
    qos-port: 22222
    enable-file-cache: off
  protocol:
    name: tri
    port: -1
  registry:
    address: zookeeper://xx.xx.xx.xx?client=curator